---
title: Irreo Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    author: andrea
    avatar: "/assets/images/avatar_andrea.jpg"
- scope:
    path: _drafts
    type: posts
  values:
    layout: post
    author: andrea
    avatar: "/assets/images/avatar_andrea.jpg"
- scope:
    path: _pages
  values:
    layout: page
name: Irreo Blog
description: Irreo Blog
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: 
email: info@nodriver.ai
mailchimp-list: https://nodriver.us1.list-manage.com/subscribe/post?u=847b32553f0cca6281a7a8570&amp;id=03f062b7ec
facebook: https://www.facebook.com/irreo.nodriver
linkedin: https://www.linkedin.com/company/irreo
twitter:
  card: summary
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jemoji
authors:
  andrea:
    name: Andrea
    avatar: assets/images/avatar_andrea.png
    bio: Andrea è un esperto in telerilevamento e osservazione della Terra. Sviluppa
      strumenti di agricoltura di precisione dal 2017. È anche il co-fondatore di
      Irreo.
    email: andrea.pomente@nodriver.ai
    twitter: https://twitter.com/pomons90
    linkedin: https://www.linkedin.com/in/andreapomente
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
